### ISSUE TITLE
Protect non-GET endpoints with Firebase auth

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#137]
- If an unauthenticated (signed out) user tries to make a POST or PUT request, the backend should reject the request
- To get started (from @JDziewonski98 ), pass a user's `idToken` with every request then use Firebase's `verifyIdToken` in the backend ([docs](https://firebase.google.com/docs/auth/admin/verify-id-tokens#node.js))

<img width="700" alt="Screen Shot 2021-03-11 at 1 04 03 PM" src="https://user-images.githubusercontent.com/36117635/110833281-4292e700-826a-11eb-84cc-397301536892.png">

Might rely on #127

**Comment by JDziewonski98** [comment]
done but forgot to close
