### ISSUE TITLE
Add directions to a mural

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#138]
This will be one of the most challenging issues yet! 🚵 

One approach:
- Make a component `Directions` that takes two points as props then renders step-by-step instructions
- To get started, follow the Mapbox Directions API [tutorial](https://docs.mapbox.com/help/tutorials/getting-started-directions-api/)
- The Directions API takes two coord pairs then returns waypoints, steps in plain language, and estimated time/distance

The component will usually be used to get a user from their current location (accessible via [native Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition)) to the next mural. Something to think about is how to make this usable in tours. Trust your judgment!

Keep it simple at first and make follow-up issues! For example, the Start button functionality and showing the current step over the map could be separate issues:
<img width="500" alt="Screen Shot 2021-03-14 at 7 51 56 PM" src="https://user-images.githubusercontent.com/36117635/111088682-bd743000-84fe-11eb-80f7-7adcd2e22764.png">

**Comment by SiboYang** [comment]
Hey Ted, just want to make sure one thing, for the direction of a tour, should we come up with an algorithm that generate the shortest path to visit all of the murals in the tour from current position or I misunderstand what we should do for the direction of a tour (such as the tour have a fixed starting mural and ending mural)

**Comment by tedspare** [comment]
> Hey Ted, just want to make sure one thing, for the direction of a tour, should we come up with an algorithm that generate the shortest path to visit all of the murals in the tour from current position or I misunderstand what we should do for the direction of a tour (such as the tour have a fixed starting mural and ending mural and we just need to find the path from current position to the starting point)

Hey! Your second point is closest to my understanding of the problem. The order of murals in a tour is fixed by MU employees so it might not be an optimal route (in terms of distance) but it is intentional. Hope that helps.

**Comment by tedspare** [comment]
Closed by #149
