### ISSUE TITLE
Remove Cancel button from menu

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#142]
- According to @celinehuang from the CRM team 😡 it's not necessary
- Quick fix to feel productive
<img width="205" alt="Screen Shot 2021-03-26 at 4 56 07 PM" src="https://user-images.githubusercontent.com/36117635/112691753-2a1ef100-8e54-11eb-9513-86c8eb50a401.png">

**Comment by celinehuang** [comment]
hehe

**Comment by tedspare** [comment]
Closed by #147
