### ISSUE TITLE
Add commit, branch name, and PR syntax to README

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#17]
As a developer, I want a guideline for branch names, commit messages, and pull request descriptions

Some suggestions:
- We can standardize feature branch names to something like `feature/#-issue_title` where `#` is the related issue number and `issue_title` is the issue title in snake_case
- We can keep urgent bug fix branch names to `hotfix/description` for when there is no related issue
- Keep commit messages to present tense, imperative eg. "update README with commit message guideline" ([reason](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages#:~:text=The%20preference%20for%20present%2Dtense,messages%20comes%20from%20Git%20itself.))

**Comment by Tony9984** [comment]
@tedspare @JDziewonski98 Added guidelines in the repo wiki! Let me know if anything needs to be changed (hopefully I won't need Grammarly lol) https://github.com/hack4impact-mcgill/mu-map/wiki/Code-contribution-guidelines
