### ISSUE TITLE
Add Tour form

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#94]
Still figuring out how to approach this. If you have a good idea, go ahead!

Some half-baked ideas:

- Start by reusing some of the mural form code
- Reuse the mural search bar in Search.tsx to add murals to the tour. Collect the coords of the murals in an array.
- On submit (or after each mural), pass the mural coords to the Mapbox [directions API](https://docs.mapbox.com/api/navigation/directions/), which returns a series of [waypoints](https://docs.mapbox.com/api/navigation/directions/#example-response-retrieve-directions)

To be solved:
- How to allow murals to be re-ordered (see last photo)

Future issue:
- Render the waypoints on the Map with [GeoJSON lines](https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/)

<img width="496" alt="Screen Shot 2021-01-27 at 9 30 45 PM" src="https://user-images.githubusercontent.com/36117635/106081455-ed01e100-60e6-11eb-9ad2-6d2bdcb7f4d5.png">

<img width="484" alt="Screen Shot 2021-01-27 at 9 31 15 PM" src="https://user-images.githubusercontent.com/36117635/106081501-fee38400-60e6-11eb-8efc-287666d9a761.png">

**Comment by tedspare** [comment]
Consider using `react-beautiful-dnd` like this [example](https://codesandbox.io/s/4qp6vjp319?file=/index.js:0-93) for the drag and drop functionality

**Comment by JDziewonski98** [comment]
form working, could use some work on styling

**Comment by tedspare** [comment]
Closed by #131
